export const ActivityType = Object.freeze({
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",

  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_DELETED: "PROJECT_DELETED",
  PROJECT_MEMBER_ADDED: "PROJECT_MEMBER_ADDED",
  PROJECT_MEMBER_REMOVED: "PROJECT_MEMBER_REMOVED",
  PROJECT_MEMBER_ROLE_CHANGED: "PROJECT_MEMBER_ROLE_CHANGED",

  SPRINT_CREATED: "SPRINT_CREATED",
  SPRINT_UPDATED: "SPRINT_UPDATED",
  SPRINT_DELETED: "SPRINT_DELETED",
  SPRINT_STARTED: "SPRINT_STARTED",
  SPRINT_COMPLETED: "SPRINT_COMPLETED",
  SPRINT_CLOSED: "SPRINT_CLOSED",

  TICKET_CREATED: "TICKET_CREATED",
  TICKET_UPDATED: "TICKET_UPDATED",
  TICKET_DELETED: "TICKET_DELETED",
  TICKET_ASSIGNED: "TICKET_ASSIGNED",
  TICKET_UNASSIGNED: "TICKET_UNASSIGNED",
  TICKET_STATUS_CHANGED: "TICKET_STATUS_CHANGED",
  TICKET_PRIORITY_CHANGED: "TICKET_PRIORITY_CHANGED",
  TICKET_MOVED_TO_SPRINT: "TICKET_MOVED_TO_SPRINT",

  COMMENT_ADDED: "COMMENT_ADDED",
  COMMENT_UPDATED: "COMMENT_UPDATED",
  COMMENT_DELETED: "COMMENT_DELETED",

  ACTIVITY_LOG_CLEARED: "ACTIVITY_LOG_CLEARED",
  SYSTEM_MIGRATION: "SYSTEM_MIGRATION",
  NOTIFICATION_SENT: "NOTIFICATION_SENT",
});


